name: randomize
version: 0.0.4
author: Marcus Wendt <marcus@field.io>
description: Random number generation utilities for Dart.
homepage: https://github.com/field/randomize.dart
dependencies:
  vector_math: '>=1.4.2+1 <2.0.0'
